name = "ChemicalEquations"
uuid = "f49a7eeb-7498-4999-b1d8-e30dc4dd315a"
authors = ["Reginaldo Gonçalves Leão Junior <prof.reginaldo.leao@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebraX = "9b3f67b0-2d00-526e-9884-9e4938f8fb88"

[compat]
DocStringExtensions = "0.9.3"
LinearAlgebraX = "0.2.10"
